# Generated by Django 6.0.2 on 2026-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_quizattempt_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_correct",
        ),
    ]
