# Generated by Django 6.0.2 on 2026-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_remove_answer_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(),
        ),
    ]
