# Generated by Django 6.0.2 on 2026-03-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_explanation_alter_question_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
