# Generated by Django 6.0.2 on 2026-03-25 14:32

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_question_owner_quiz_owner_quizattempt_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True, related_name="shared_quizzes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="quiz",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                    ("shared", "Shared with users"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
