# Generated by Django 6.0.2 on 2026-03-25 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quiz_allowed_users_quiz_share_token_quiz_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="share_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
