# Generated by Django 6.0.2 on 2026-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_alter_quiz_share_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("unlisted", "Unlisted"),
                    ("shared", "Shared with users"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
