# Generated by Django 6.0.2 on 2026-03-26 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_alter_quizattempt_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="token",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
