# Generated by Django 6.0.2 on 2026-03-26 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_quizattempt_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
