# Generated by Django 6.0.2 on 2026-04-12 15:21

from django.db import migrations

def migrate_allowed_users(apps, schema_editor):
    Quiz = apps.get_model("quiz", "Quiz")
    QuizAccess = apps.get_model("quiz", "QuizAccess")

    for quiz in Quiz.objects.all():
        for user in quiz.allowed_users.all():
            QuizAccess.objects.create(
                user=user,
                quiz=quiz
            )

class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0016_quizaccess"),
    ]

    operations = [
        migrations.RunPython(migrate_allowed_users),
    ]
