# Generated by Django 6.0.2 on 2026-04-12 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_auto_20260412_1721"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_quizzes",
                through="quiz.QuizAccess",
                through_fields=("quiz", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
