# Generated by Django 6.0.2 on 2026-04-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0017_auto_20260412_1721"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="allowed_users",
        ),
    ]
